[package]
name = "breakfast"
version = "0.1.0"
authors = ["Matti Annala <matti.annala@uta.fi>", "Gnanavel Mutharasu <gnanavel.mutharasu@gmail.com>"]

[dependencies]
docopt = "*"
bio = "*"
regex = "*"
rust-htslib = "*"
