[package]
name = "breakfastrs"
version = "0.1.0"
authors = ["Gnanavel Mutharasu <gnanavel.mutharasu@gmail.com>"]

[dependencies]
clap = "*"
bio = "*"
rust-htslib = "*"
regex = "0.2"
subprocess= "*"
shells = "*"
