[package]
name = "breakfast"
version = "0.1.0"
authors = ["Matti Annala <matti.annala@uta.fi>", "Gnanavel Mutharasu <gnanavel.mutharasu@gmail.com>"]
description = "Breakfast is a software for detecting structural variants from DNA sequencing data"
readme = "README.md"
keywords = ["breakfast", "RNA-Seq", "fusion-genes", "bioinformatics", "rearrangements", "sequencing"]
license = "MIT"
repository = "https://github.com/annalam/breakfast.git"

[dependencies]
docopt = "*"
bio = "*"
regex = "*"
rust-htslib = "*"
